on:
  issue_comment:
    types: [created]

name: Issue Comment Created

permissions:
  contents: read
  issues: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get_ref.outputs.ref }}
    steps:
      - name: Determine Active Ref
        id: get_ref
        run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/issues/$ISSUE_NUMBER --jq '.labels.[].name')"
          for label in "${labels[@]}"
          do
            if [[ "$label" == "development" ]]; then
              echo "ref=dev" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          done
          echo "ref=main" >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
  call-main-workflow:
    needs: [setup]
    if: ${{ needs.setup.outputs.ref == 'main' }}
    uses: digimangos-playground/issueop-dev-flow-test/.github/workflows/reusable-workflow.yml@main
  call-dev-workflow:
    needs: [setup]
    if: ${{ needs.setup.outputs.ref == 'dev' }}
    uses: digimangos-playground/issueop-dev-flow-test/.github/workflows/reusable-workflow.yml@dev
